# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


# Do not change the code made by Qt Designer
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(400, 550)  # setFixedSize doesn't allow to change a window size
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 400, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.label_result.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_result.setObjectName("label_result")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 350, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 350, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 350, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 250, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 250, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 250, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 150, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 150, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 150, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 450, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(255, 195, 135);\n"
                                        "")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(0, 50, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgb(255, 172, 123);\n"
                                            "")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_backspace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_backspace.setGeometry(QtCore.QRect(100, 50, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_backspace.setFont(font)
        self.pushButton_backspace.setStyleSheet("background-color: rgb(255, 172, 123);\n"
                                                "")
        self.pushButton_backspace.setObjectName("pushButton_backspace")
        self.pushButton_plus_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus_minus.setGeometry(QtCore.QRect(200, 50, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_plus_minus.setFont(font)
        self.pushButton_plus_minus.setStyleSheet("background-color: rgb(255, 172, 123);")
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(300, 50, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setStyleSheet("background-color: rgb(255, 172, 123);")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(300, 150, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("background-color: rgb(255, 172, 123);\n"
                                               "")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(300, 250, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("background-color: rgb(255, 172, 123);\n"
                                            "")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(300, 350, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("background-color: rgb(255, 172, 123);")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(200, 450, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setStyleSheet("background-color: rgb(255, 172, 123);\n"
                                          "")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_equal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(300, 450, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setStyleSheet("background-color: rgb(255, 124, 30);\n"
                                            "")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.label_result.raise_()
        self.pushButton_clear.raise_()
        self.pushButton_backspace.raise_()
        self.pushButton_plus_minus.raise_()
        self.pushButton_divide.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_multiply.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_minus.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_plus.raise_()
        self.pushButton_0.raise_()
        self.pushButton_dot.raise_()
        self.pushButton_equal.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_backspace.setText(_translate("MainWindow", "⌫"))
        self.pushButton_plus_minus.setText(_translate("MainWindow", "+/–"))
        self.pushButton_divide.setText(_translate("MainWindow", "/"))
        self.pushButton_multiply.setText(_translate("MainWindow", "*"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_equal.setText(_translate("MainWindow", "="))

    # Event handling
    def add_functions(self):
        # Lambda is necessary
        self.pushButton_0.clicked.connect(lambda: self.write(self.pushButton_0.text()))
        self.pushButton_1.clicked.connect(lambda: self.write(self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(lambda: self.write(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda: self.write(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda: self.write(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda: self.write(self.pushButton_9.text()))
        self.pushButton_plus.clicked.connect(lambda: self.write(self.pushButton_plus.text()))
        self.pushButton_minus.clicked.connect(lambda: self.write(self.pushButton_minus.text()))
        self.pushButton_multiply.clicked.connect(lambda: self.write(self.pushButton_multiply.text()))
        self.pushButton_divide.clicked.connect(lambda: self.write(self.pushButton_divide.text()))
        self.pushButton_dot.clicked.connect(lambda: self.write(self.pushButton_dot.text()))

        self.pushButton_plus_minus.clicked.connect(lambda: self.sign())

        self.pushButton_backspace.clicked.connect(lambda: self.back())

        self.pushButton_clear.clicked.connect(lambda: self.cls())

        self.pushButton_equal.clicked.connect(lambda: self.result())

    # Changing the sign before the number
    def sign(self):
        if self.label_result.text()[0] == "-":
            self.label_result.setText(self.label_result.text()[1::])
        else:
            self.label_result.setText("-" + self.label_result.text())

    # Deleting one symbol to the right
    def back(self):
        if len(self.label_result.text()) == 1:
            self.label_result.setText("0")
        else:
            self.label_result.setText(self.label_result.text()[:-1])

    # Clear everything
    def cls(self):
        self.label_result.setText("0")

    # Counting
    def result(self):
        try:
            self.label_result.setText(str(eval(self.label_result.text())))
        except Exception:
            self.label_result.setText("ERROR")

    # Responsible for writing symbols to the result field
    def write(self, symbol):
        if self.label_result.text() in ("0", "ERROR"):
            self.label_result.setText(str(symbol))
        else:
            self.label_result.setText(self.label_result.text() + str(symbol))


# Class required for keyPressEvent (pressing keys on real keyboard)
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)

    def keyPressEvent(self, e):
        a = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "+", "-", "*", "/", "."]
        for i in a:
            if e.text() == i:
                self.write(e.text())
        if e.key() == QtCore.Qt.Key_Backspace:
            self.back()
        if e.key() == QtCore.Qt.Key_Return:
            self.result()
        if e.text() in ("c", "с"):
            self.cls()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())
